spring.application.name=lab1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=lab_user
spring.datasource.password=lab_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# EclipseLink
spring.jpa.properties.eclipselink.logging.level=INFO
spring.jpa.properties.eclipselink.target-database=PostgreSQL
spring.jpa.properties.eclipselink.ddl-generation=create-or-extend-tables
spring.jpa.properties.eclipselink.ddl-generation.output-mode=database
