<dependencies>
    <dependency>
        <groupId>io.github.qsy7.java.dependencies</groupId>
        <artifactId>jakarta-servlet</artifactId>
        <version>0.3.3</version>
    </dependency>
    <dependency>
        <groupId>io.github.thinkbinny.framework</groupId>
        <artifactId>spring-web-mvc</artifactId>
        <version>3.0.0</version>
    </dependency>
    <dependency>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>eclipselink</artifactId>
        <version>5.0.1</version>
    </dependency>
    <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.7.13</version>
    </dependency>
</dependencies>

<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.5.1</version>
    </plugin>
</plugins>
